GET http://localhost:3001/api/persons
###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Anna",
    "number": "0401234556"
}

###
# DELETE https://mylittlewebpage.onrender.com/api/persons/66991985891b3f332d4e2325
DELETE http://localhost:3001/api/persons/6
###
PUT http://localhost:3001/api/persons/669965d8a5c8069e7f5bbf1e
content-type: application/json

{
    "number": "420noscopelmao"
}